import { SaveServer } from "../servers/SaveServer";
import { DatabaseServer } from "../servers/DatabaseServer";
import { ITemplateItem } from "../models/eft/common/tables/ITemplateItem";
import { ItemHelper } from "./ItemHelper";
import { ProfileHelper } from "./ProfileHelper";
import { MemberCategory } from "../models/eft/common/MemberCategory";
import { ConfigServer } from "../servers/ConfigServer";
import { RandomUtil } from "../utils/RandomUtil";
import { DialogueHelper } from "./DialogueHelper";
import { Item } from "../models/eft/common/tables/IItem";
import { JsonUtil } from "../utils/JsonUtil";
import { HashUtil } from "../utils/HashUtil";
export declare class RagfairServerHelper {
    private randomUtil;
    private hashUtil;
    private saveServer;
    private databaseServer;
    private profileHelper;
    private itemHelper;
    private dialogueHelper;
    private jsonUtil;
    private configServer;
    private ragfairConfig;
    private questConfig;
    private static TPL_GOODS_RETURNED;
    constructor(randomUtil: RandomUtil, hashUtil: HashUtil, saveServer: SaveServer, databaseServer: DatabaseServer, profileHelper: ProfileHelper, itemHelper: ItemHelper, dialogueHelper: DialogueHelper, jsonUtil: JsonUtil, configServer: ConfigServer);
    isItemValidRagfairItem(itemDetails: [boolean, ITemplateItem]): boolean;
    isItemBlacklisted(itemTemplateId: string): boolean;
    isTrader(userID: string): boolean;
    isPlayer(userID: string): boolean;
    returnItems(sessionID: string, items: any[]): void;
    calculateDynamicStackCount(tplId: string, isWeaponPreset: boolean): number;
    getDynamicOfferCurrency(): string;
    getMemberType(userID: string): MemberCategory;
    getNickname(userID: string): string;
    getPresetItems(item: any): Item[];
    getPresetItemsByTpl(item: Item): Item[];
    reparentPresets(item: Item, preset: Item[]): Item[];
}
