import { RagfairServer } from "../servers/RagfairServer";
import { RagfairController } from "../controllers/RagfairController";
import { IPmcData } from "../models/eft/common/IPmcData";
import { IGetBodyResponseData } from "../models/eft/httpResponse/IGetBodyResponseData";
import { ISearchRequestData } from "../models/eft/ragfair/ISearchRequestData";
import { IEmptyRequestData } from "../models/eft/common/IEmptyRequestData";
import { IGetMarketPriceRequestData } from "../models/eft/ragfair/IGetMarketPriceRequestData";
import { IAddOfferRequestData } from "../models/eft/ragfair/IAddOfferRequestData";
import { IRemoveOfferRequestData } from "../models/eft/ragfair/IRemoveOfferRequestData";
import { IExtendOfferRequestData } from "../models/eft/ragfair/IExtendOfferRequestData";
import { IItemEventRouterResponse } from "../models/eft/itemEvent/IItemEventRouterResponse";
import { IGetItemPriceResult } from "../models/eft/ragfair/IGetItemPriceResult";
import { ConfigServer } from "../servers/ConfigServer";
import { HttpResponseUtil } from "../utils/HttpResponseUtil";
import { JsonUtil } from "../utils/JsonUtil";
import { OnLoadOnUpdate } from "../di/OnLoadOnUpdate";
import { ILogger } from "../models/spt/utils/ILogger";
export declare class RagfairCallbacks extends OnLoadOnUpdate {
    private httpResponse;
    private logger;
    private jsonUtil;
    private ragfairServer;
    private ragfairController;
    private configServer;
    private ragfairConfig;
    constructor(httpResponse: HttpResponseUtil, logger: ILogger, jsonUtil: JsonUtil, ragfairServer: RagfairServer, ragfairController: RagfairController, configServer: ConfigServer);
    onLoad(): void;
    getRoute(): string;
    search(url: string, info: ISearchRequestData, sessionID: string): IGetBodyResponseData<any>;
    getMarketPrice(url: string, info: IGetMarketPriceRequestData, sessionID: string): IGetBodyResponseData<IGetItemPriceResult>;
    getItemPrices(url: string, info: IEmptyRequestData, sessionID: string): IGetBodyResponseData<any>;
    addOffer(pmcData: IPmcData, info: IAddOfferRequestData, sessionID: string): IItemEventRouterResponse;
    removeOffer(pmcData: IPmcData, info: IRemoveOfferRequestData, sessionID: string): IItemEventRouterResponse;
    extendOffer(pmcData: IPmcData, info: IExtendOfferRequestData, sessionID: string): IItemEventRouterResponse;
    onUpdate(timeSinceLastRun: number): boolean;
}
