import { HttpResponse } from "../utils/HttpResponse";
import { HashUtil } from "../utils/HashUtil";
import { TimeUtil } from "../utils/TimeUtil";
import { DialogueController } from "../controllers/DialogueController";
import { IGetBodyResponseData } from "../@types/eft/httpResponse/IGetBodyResponseData";
import { DialogueInfo } from "../@types/eft/profile/IAkiProfile";
import { INullResponseData } from "../@types/eft/httpResponse/INullResponseData";
import { IGetMailDialogViewRequestData } from "../@types/eft/dialog/IGetMailDialogViewRequestData";
import { IGetMailDialogInfoRequestData } from "../@types/eft/dialog/IGetMailDialogInfoRequestData";
import { IRemoveDialogRequestData } from "../@types/eft/dialog/IRemoveDialogRequestData";
import { IGetMailDialogListRequestData } from "../@types/eft/dialog/IGetMailDialogListRequestData";
import { IEmptyRequestData } from "../@types/eft/common/IEmptyRequestData";
import { IFriendRequestData } from "../@types/eft/dialog/IFriendRequestData";
import { IPinDialogRequestData } from "../@types/eft/dialog/IPinDialogRequestData";
import { ISetDialogReadRequestData } from "../@types/eft/dialog/ISetDialogReadRequestData";
import { IGetAllAttachmentsRequestData } from "../@types/eft/dialog/IGetAllAttachmentsRequestData";
import { IGetChatServerListRequestData } from "../@types/eft/dialog/IGetChatServerListRequestData";
import { IGetFriendListDataResponse } from "../@types/eft/dialog/IGetFriendListDataResponse";
import { ISendMessageRequest } from "../@types/eft/dialog/ISendMessageRequest";
import { IGetMailDialogViewResponseData } from "../@types/eft/dialog/IGetMailDialogViewResponseData";
import { IGetAllAttachmentsResponse } from "../@types/eft/dialog/IGetAllAttachmentsResponse";
import { OnUpdate } from "../di/OnUpdate";
export declare class DialogueCallbacks extends OnUpdate {
    private hashUtil;
    private timeUtil;
    private httpResponse;
    private dialogueController;
    constructor(hashUtil: HashUtil, timeUtil: TimeUtil, httpResponse: HttpResponse, dialogueController: DialogueController);
    getFriendList(url: string, info: IEmptyRequestData, sessionID: string): IGetBodyResponseData<IGetFriendListDataResponse>;
    getChatServerList(url: string, info: IGetChatServerListRequestData, sessionID: string): IGetBodyResponseData<any[]>;
    getMailDialogList(url: string, info: IGetMailDialogListRequestData, sessionID: string): IGetBodyResponseData<DialogueInfo[]>;
    getMailDialogView(url: string, info: IGetMailDialogViewRequestData, sessionID: string): IGetBodyResponseData<IGetMailDialogViewResponseData>;
    getMailDialogInfo(url: string, info: IGetMailDialogInfoRequestData, sessionID: string): IGetBodyResponseData<any>;
    removeDialog(url: string, info: IRemoveDialogRequestData, sessionID: string): IGetBodyResponseData<any[]>;
    pinDialog(url: string, info: IPinDialogRequestData, sessionID: string): IGetBodyResponseData<any[]>;
    unpinDialog(url: string, info: IPinDialogRequestData, sessionID: string): IGetBodyResponseData<any[]>;
    setRead(url: string, info: ISetDialogReadRequestData, sessionID: string): IGetBodyResponseData<any[]>;
    getAllAttachments(url: string, info: IGetAllAttachmentsRequestData, sessionID: string): IGetBodyResponseData<IGetAllAttachmentsResponse>;
    listOutbox(url: string, info: IEmptyRequestData, sessionID: string): IGetBodyResponseData<any[]>;
    listInbox(url: string, info: IEmptyRequestData, sessionID: string): IGetBodyResponseData<any[]>;
    friendRequest(url: string, request: IFriendRequestData, sessionID: string): INullResponseData;
    sendMessage(url: string, request: ISendMessageRequest, sessionID: string): IGetBodyResponseData<number>;
    onUpdate(timeSinceLastRun: number): boolean;
    getRoute(): string;
}
