import { IPmcData } from "../@types/eft/common/IPmcData";
import { Item } from "../@types/eft/common/tables/IItem";
import { ISaveProgressRequestData } from "../@types/eft/inRaid/ISaveProgressRequestData";
import { IInsuranceConfig } from "../@types/spt/config/IInsuranceConfig";
import { ILogger } from "../@types/spt/utils/ILogger";
import { DialogueHelper } from "../helpers/DialogueHelper";
import { InventoryHelper } from "../helpers/InventoryHelper";
import { TraderHelper } from "../helpers/TraderHelper";
import { ConfigServer } from "../servers/ConfigServer";
import { DatabaseServer } from "../servers/DatabaseServer";
import { SaveServer } from "../servers/SaveServer";
import { RandomUtil } from "../utils/RandomUtil";
import { TimeUtil } from "../utils/TimeUtil";
export declare class InsuranceService {
    private logger;
    private databaseServer;
    private inventoryHelper;
    private randomUtil;
    private timeUtil;
    private saveServer;
    private traderHelper;
    private dialogueHelper;
    private configServer;
    private insured;
    private templatesById;
    insuranceConfig: IInsuranceConfig;
    constructor(logger: ILogger, databaseServer: DatabaseServer, inventoryHelper: InventoryHelper, randomUtil: RandomUtil, timeUtil: TimeUtil, saveServer: SaveServer, traderHelper: TraderHelper, dialogueHelper: DialogueHelper, configServer: ConfigServer);
    insuranceExists(sessionId: string): boolean;
    insuranceTraderArrayExists(sessionId: string, traderId: string): boolean;
    getInsurance(sessionId: string): Record<string, Item[]>;
    getInsuranceItems(sessionId: string, traderId: string): any[];
    resetInsurance(sessionId: string): void;
    resetInsuranceTraderArray(sessionId: string, traderId: string): void;
    addInsuranceItemToArray(sessionId: string, traderId: string, itemToAdd: any): void;
    getItemPrice(_tpl: string): number;
    generateTemplatesById(): void;
    sendInsuredItems(pmcData: IPmcData, sessionID: string): void;
    storeLostGear(pmcData: IPmcData, offraidData: ISaveProgressRequestData, preRaidGear: Item[], sessionID: string): void;
    storeInsuredItemsForReturn(pmcData: IPmcData, offraidData: ISaveProgressRequestData, preRaidGear: Item[], sessionID: string): void;
    private addGearToSend;
    getPremium(pmcData: IPmcData, inventoryItem: Item, traderId: string): number;
}
